name: feed_generator
description: Feed Generator for @skyfeed.xyz
version: 1.0.0

environment:
  sdk: ^3.0.3

dependencies:
  alfred: ^1.1.0+2
  cbor: ^5.1.2
  http: ^1.0.0
  influxdb_client: ^2.9.0
  lib5: ^0.1.0
  thirds: ^0.2.0-alpha.1
  indexer:
    git: https://github.com/skyfeed-dev/indexer.git

dependency_overrides:
  http: 1.0.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
